/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.tribosmap;

public final class R {
    public static final class anim {
        public static final int fade_out=0x7f040000;
        public static final int layout_fade_out=0x7f040001;
        public static final int layout_slide_in_down=0x7f040002;
        public static final int layout_slide_in_left=0x7f040003;
        public static final int layout_slide_in_right=0x7f040004;
        public static final int layout_slide_in_up=0x7f040005;
        public static final int slide_in_down=0x7f040006;
        public static final int slide_in_left=0x7f040007;
        public static final int slide_in_right=0x7f040008;
        public static final int slide_in_up=0x7f040009;
    }
    public static final class array {
        public static final int hemisphere=0x7f060000;
        public static final int languages=0x7f060001;
    }
    public static final class attr {
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int src=0x7f010003;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int src_off=0x7f010001;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int text=0x7f010002;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int text_off=0x7f010000;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int text_size=0x7f010004;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int wrapLayout=0x7f010005;
    }
    public static final class drawable {
        public static final int a1=0x7f020000;
        public static final int a2=0x7f020001;
        public static final int a3=0x7f020002;
        public static final int a4=0x7f020003;
        public static final int b1=0x7f020004;
        public static final int b2=0x7f020005;
        public static final int b3=0x7f020006;
        public static final int b4=0x7f020007;
        public static final int background=0x7f020064;
        public static final int backkachel=0x7f020008;
        public static final int black_box=0x7f020009;
        public static final int box=0x7f02000a;
        public static final int c1=0x7f02000b;
        public static final int c2=0x7f02000c;
        public static final int c3=0x7f02000d;
        public static final int c4=0x7f02000e;
        public static final int cancel=0x7f02000f;
        public static final int create_marker=0x7f020010;
        public static final int create_marker_inverted=0x7f020011;
        public static final int create_marker_selector=0x7f020012;
        public static final int d1=0x7f020013;
        public static final int d2=0x7f020014;
        public static final int d3=0x7f020015;
        public static final int d4=0x7f020016;
        public static final int delete=0x7f020017;
        public static final int delete_inverted=0x7f020018;
        public static final int delete_selector=0x7f020019;
        public static final int delete_small=0x7f02001a;
        public static final int delete_small_inverted=0x7f02001b;
        public static final int delete_small_selector=0x7f02001c;
        public static final int editf=0x7f02001d;
        public static final int editf_inverted=0x7f02001e;
        public static final int editf_selector=0x7f02001f;
        public static final int exportf=0x7f020020;
        public static final int exportf_inverted=0x7f020021;
        public static final int exportf_selector=0x7f020022;
        public static final int file_map=0x7f020023;
        public static final int file_marker=0x7f020024;
        public static final int file_trace=0x7f020025;
        public static final int folder=0x7f020026;
        public static final int greenball=0x7f020027;
        public static final int greenball_small=0x7f020028;
        public static final int home=0x7f020029;
        public static final int home_inverted=0x7f02002a;
        public static final int home_selector=0x7f02002b;
        public static final int icon=0x7f02002c;
        public static final int icon_tribos=0x7f02002d;
        public static final int image=0x7f02002e;
        public static final int importf=0x7f02002f;
        public static final int importf_inverted=0x7f020030;
        public static final int importf_selector=0x7f020031;
        public static final int main_map=0x7f020032;
        public static final int main_map_inverted=0x7f020033;
        public static final int main_map_selector=0x7f020034;
        public static final int main_marker=0x7f020035;
        public static final int main_marker_inverted=0x7f020036;
        public static final int main_marker_selector=0x7f020037;
        public static final int main_quit=0x7f020038;
        public static final int main_quit_inverted=0x7f020039;
        public static final int main_quit_selector=0x7f02003a;
        public static final int main_trace=0x7f02003b;
        public static final int main_trace_inverted=0x7f02003c;
        public static final int main_trace_selector=0x7f02003d;
        public static final int map_auto_center=0x7f02003e;
        public static final int map_icon=0x7f02003f;
        public static final int map_select=0x7f020040;
        public static final int map_select_inverted=0x7f020041;
        public static final int mapimage=0x7f020042;
        public static final int marker_create_selector=0x7f020043;
        public static final int marker_green=0x7f020044;
        public static final int marker_red=0x7f020045;
        public static final int marker_white=0x7f020046;
        public static final int menu_delete=0x7f020047;
        public static final int menu_edit=0x7f020048;
        public static final int menu_export=0x7f020049;
        public static final int menu_home=0x7f02004a;
        public static final int menu_import=0x7f02004b;
        public static final int menu_open=0x7f02004c;
        public static final int ok=0x7f02004d;
        public static final int plus=0x7f02004e;
        public static final int record=0x7f02004f;
        public static final int record_inverted=0x7f020050;
        public static final int record_selector=0x7f020051;
        public static final int record_trace=0x7f020052;
        public static final int record_trace_inverted=0x7f020053;
        public static final int record_trace_selector=0x7f020054;
        public static final int redball=0x7f020055;
        public static final int redball_small=0x7f020056;
        public static final int selected=0x7f020063;
        public static final int star=0x7f020057;
        public static final int stop_record_trace=0x7f020058;
        public static final int stop_record_trace_inverted=0x7f020059;
        public static final int stop_record_trace_selector=0x7f02005a;
        public static final int trace_icon=0x7f02005b;
        public static final int view=0x7f02005c;
        public static final int view_inverted=0x7f02005d;
        public static final int view_selector=0x7f02005e;
        public static final int view_small=0x7f02005f;
        public static final int view_small_inverted=0x7f020060;
        public static final int view_small_selector=0x7f020061;
        public static final int warning=0x7f020062;
        public static final int white=0x7f020065;
    }
    public static final class id {
        public static final int auto_center=0x7f09004e;
        public static final int btn=0x7f090007;
        public static final int camera_btn=0x7f090035;
        public static final int cancel_btn=0x7f090004;
        public static final int checkCenter=0x7f090030;
        public static final int checkMarker=0x7f090031;
        public static final int coord_flipper=0x7f090037;
        public static final int coord_ll_view=0x7f090038;
        public static final int coord_switch_latlon=0x7f090044;
        public static final int coord_switch_radio=0x7f090042;
        public static final int coord_switch_utm=0x7f090043;
        public static final int coord_utm_view=0x7f09003b;
        public static final int created=0x7f090023;
        public static final int delete_btn=0x7f090047;
        public static final int edit_altitude=0x7f090041;
        public static final int edit_btn=0x7f09004d;
        public static final int edit_file_name=0x7f090003;
        public static final int edit_information=0x7f090036;
        public static final int edit_latitude=0x7f090039;
        public static final int edit_longitude=0x7f09003a;
        public static final int edit_marker_image_view=0x7f090045;
        public static final int edit_marker_main=0x7f090020;
        public static final int edit_name=0x7f090021;
        public static final int edit_utm_east=0x7f09003d;
        public static final int edit_utm_north=0x7f09003c;
        public static final int edit_utm_zone=0x7f09003f;
        public static final int edit_utm_zone_row=0x7f09003e;
        public static final int errortext=0x7f090001;
        public static final int export_btn=0x7f09004f;
        public static final int file_dir_text=0x7f090002;
        public static final int hemisphere=0x7f090040;
        public static final int image_view=0x7f090046;
        public static final int import_btn=0x7f09004b;
        public static final int lblAltitude=0x7f090010;
        public static final int lblCenterTitle=0x7f090033;
        public static final int lblLatitude=0x7f090011;
        public static final int lblLongitude=0x7f090012;
        public static final int lblMarkerTitle=0x7f090034;
        public static final int lblZoom=0x7f09002d;
        public static final int lblZoomTitle=0x7f09002c;
        public static final int left_up_latitude=0x7f090027;
        public static final int left_up_longitude=0x7f090028;
        public static final int length=0x7f090048;
        public static final int main_create_marker_btn=0x7f090016;
        public static final int main_import_btn=0x7f090017;
        public static final int main_map_btn=0x7f090014;
        public static final int main_marker_btn=0x7f090013;
        public static final int main_menu=0x7f09000e;
        public static final int main_osmview_btn=0x7f09001b;
        public static final int main_quit_btn=0x7f09001a;
        public static final int main_record_btn=0x7f090018;
        public static final int main_trace_btn=0x7f090015;
        public static final int map_image=0x7f090022;
        public static final int menu_group=0x7f09004a;
        public static final int ok_btn=0x7f090006;
        public static final int open_btn=0x7f09004c;
        public static final int pointcount=0x7f090049;
        public static final int postext=0x7f09000f;
        public static final int record_trace_distance=0x7f09001f;
        public static final int record_trace_pointcount=0x7f09001d;
        public static final int record_trace_text=0x7f09001c;
        public static final int record_trace_text2=0x7f09001e;
        public static final int right_down_latitude=0x7f090029;
        public static final int right_down_longitude=0x7f09002a;
        public static final int row_icon=0x7f09000a;
        public static final int row_information=0x7f09000d;
        public static final int row_subtitle=0x7f09000c;
        public static final int row_title=0x7f09000b;
        public static final int save_btn=0x7f090005;
        public static final int scale=0x7f090026;
        public static final int size_x=0x7f090024;
        public static final int size_y=0x7f090025;
        public static final int stacktracebtn=0x7f090000;
        public static final int status=0x7f090009;
        public static final int text=0x7f090008;
        public static final int view=0x7f09002b;
        public static final int widget33=0x7f090019;
        public static final int widget37=0x7f09002e;
        public static final int widget38=0x7f09002f;
        public static final int widget39=0x7f090032;
    }
    public static final class layout {
        public static final int empty=0x7f030000;
        public static final int error_dialog=0x7f030001;
        public static final int file_list=0x7f030002;
        public static final int image_text_button=0x7f030003;
        public static final int init=0x7f030004;
        public static final int list_entry=0x7f030005;
        public static final int main_menu=0x7f030006;
        public static final int map_edit=0x7f030007;
        public static final int mapview=0x7f030008;
        public static final int marker_edit=0x7f030009;
        public static final int marker_image_view=0x7f03000a;
        public static final int trace_edit=0x7f03000b;
    }
    public static final class menu {
        public static final int import_list=0x7f080000;
        public static final int map_list=0x7f080001;
        public static final int map_view=0x7f080002;
        public static final int marker_list=0x7f080003;
        public static final int trace_list=0x7f080004;
    }
    public static final class string {
        public static final int altitude=0x7f070042;
        public static final int altitude_label=0x7f070043;
        public static final int app_file=0x7f070007;
        public static final int app_map=0x7f070002;
        public static final int app_map_import=0x7f070003;
        public static final int app_mapview=0x7f070006;
        public static final int app_marker=0x7f070005;
        public static final int app_name=0x7f070001;
        public static final int app_trace=0x7f070004;
        public static final int autocenter=0x7f07005c;
        public static final int back_to_main=0x7f07001b;
        public static final int cancel=0x7f070048;
        public static final int cannot_open_file_write=0x7f070061;
        public static final int created=0x7f070051;
        public static final int date_of_creation=0x7f07001c;
        public static final int deg_east=0x7f07003c;
        public static final int deg_north=0x7f07003d;
        public static final int degree=0x7f070039;
        public static final int degree_east=0x7f07003a;
        public static final int degree_north=0x7f07003b;
        public static final int delete=0x7f07002b;
        public static final int dialog_no=0x7f070017;
        public static final int dialog_question=0x7f070010;
        public static final int dialog_question_cancel_edit=0x7f070015;
        public static final int dialog_question_delete=0x7f070012;
        public static final int dialog_question_import=0x7f070014;
        public static final int dialog_question_overwrite=0x7f070013;
        public static final int dialog_question_quit=0x7f070011;
        public static final int dialog_yes=0x7f070016;
        public static final int discard_changes=0x7f070027;
        public static final int distance_label=0x7f070053;
        public static final int easting_label=0x7f070034;
        /**  new 
         */
        public static final int edit=0x7f070028;
        public static final int english=0x7f070059;
        public static final int export=0x7f070029;
        public static final int file_prefix=0x7f07002e;
        /**  import map 
         */
        public static final int file_size_prefix=0x7f07002d;
        public static final int folder_prefix=0x7f07002f;
        public static final int german=0x7f070058;
        public static final int hello=0x7f070000;
        public static final int image_deleted=0x7f070070;
        public static final int image_size=0x7f07004e;
        public static final int importf=0x7f07002c;
        public static final int information=0x7f070031;
        public static final int lat_lon=0x7f070047;
        public static final int latitude=0x7f07003e;
        public static final int latitude_label=0x7f070040;
        /**  edit map 
         */
        public static final int left_up=0x7f07004a;
        public static final int length=0x7f070056;
        public static final int length_label=0x7f070054;
        public static final int longitude=0x7f07003f;
        public static final int longitude_label=0x7f070041;
        public static final int main_create_marker=0x7f07000f;
        public static final int main_map=0x7f070008;
        public static final int main_map_import=0x7f07000c;
        public static final int main_marker=0x7f07000a;
        public static final int main_osmview=0x7f070057;
        public static final int main_quit=0x7f07000b;
        public static final int main_record_trace=0x7f07000d;
        public static final int main_stop_record_trace=0x7f07000e;
        public static final int main_trace=0x7f070009;
        public static final int map=0x7f070050;
        public static final int map_delete=0x7f07001a;
        public static final int map_deleted=0x7f070073;
        public static final int map_exporting=0x7f070072;
        public static final int map_import=0x7f070019;
        public static final int map_loading=0x7f070071;
        public static final int map_not_saved=0x7f070075;
        public static final int map_saved=0x7f070074;
        public static final int map_view=0x7f070018;
        public static final int marker_create=0x7f070024;
        public static final int marker_deleted=0x7f070067;
        public static final int marker_edit=0x7f070026;
        public static final int marker_export=0x7f070025;
        public static final int marker_exporting=0x7f070066;
        public static final int marker_loading=0x7f070065;
        public static final int marker_not_saved=0x7f070069;
        public static final int marker_saved=0x7f070068;
        public static final int meter_per_pixel=0x7f07004d;
        public static final int meters=0x7f070038;
        /**  edit position 
         */
        public static final int name=0x7f070030;
        public static final int need_bundle=0x7f07006a;
        public static final int need_file_bundle=0x7f07006b;
        public static final int need_marker_bundle=0x7f07006c;
        public static final int need_trace_bundle=0x7f07006d;
        public static final int no_files=0x7f070020;
        public static final int north=0x7f07005a;
        public static final int northing_label=0x7f070032;
        public static final int open=0x7f07002a;
        public static final int photo_saved=0x7f07006f;
        public static final int pixel=0x7f07004f;
        public static final int point_count=0x7f070055;
        public static final int point_count_label=0x7f070052;
        public static final int position_is_needed=0x7f07006e;
        public static final int position_short_label=0x7f070044;
        public static final int position_short_label_utm=0x7f070045;
        public static final int right_down=0x7f07004b;
        public static final int save=0x7f070049;
        public static final int scale=0x7f07004c;
        public static final int selected_map=0x7f07001d;
        public static final int selected_map_cover_false=0x7f07001f;
        public static final int selected_map_cover_true=0x7f07001e;
        public static final int south=0x7f07005b;
        public static final int trace_deleted=0x7f070062;
        public static final int trace_edit=0x7f070021;
        public static final int trace_export=0x7f070022;
        public static final int trace_exported=0x7f070060;
        public static final int trace_exporting=0x7f07005f;
        public static final int trace_loading=0x7f07005d;
        public static final int trace_not_saved=0x7f070064;
        public static final int trace_record=0x7f070023;
        public static final int trace_saved=0x7f070063;
        public static final int utm=0x7f070046;
        public static final int utm_east=0x7f070035;
        public static final int utm_north=0x7f070033;
        public static final int utm_zone=0x7f070037;
        public static final int window_open=0x7f07005e;
        public static final int zone_label=0x7f070036;
    }
    public static final class xml {
        public static final int preferences=0x7f050000;
    }
    public static final class styleable {
        /** Attributes that can be used with a ImageTextButton.
           <p>Includes the following attributes:</p>
           <table border="2" width="85%" align="center" frame="hsides" rules="all" cellpadding="5">
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute<th>Summary</tr>
           <tr><th><code>{@link #ImageTextButton_src org.tribosmap:src}</code><td></tr>
           <tr><th><code>{@link #ImageTextButton_text org.tribosmap:text}</code><td></tr>
           <tr><th><code>{@link #ImageTextButton_text_size org.tribosmap:text_size}</code><td></tr>
           </table>
           @see #ImageTextButton_src
           @see #ImageTextButton_text
           @see #ImageTextButton_text_size
         */
        public static final int[] ImageTextButton = {
            0x7f010002, 0x7f010003, 0x7f010004
        };
        /**
          <p>This symbol is the offset where the {@link org.tribosmap.R.attr#src}
          attribute's value can be found in the {@link #ImageTextButton} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:src
        */
        public static final int ImageTextButton_src = 1;
        /**
          <p>This symbol is the offset where the {@link org.tribosmap.R.attr#text}
          attribute's value can be found in the {@link #ImageTextButton} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:text
        */
        public static final int ImageTextButton_text = 0;
        /**
          <p>This symbol is the offset where the {@link org.tribosmap.R.attr#text_size}
          attribute's value can be found in the {@link #ImageTextButton} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:text_size
        */
        public static final int ImageTextButton_text_size = 2;
        /** Attributes that can be used with a ImageTextSwitchButton.
           <p>Includes the following attributes:</p>
           <table border="2" width="85%" align="center" frame="hsides" rules="all" cellpadding="5">
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute<th>Summary</tr>
           <tr><th><code>{@link #ImageTextSwitchButton_src_off org.tribosmap:src_off}</code><td></tr>
           <tr><th><code>{@link #ImageTextSwitchButton_text_off org.tribosmap:text_off}</code><td></tr>
           </table>
           @see #ImageTextSwitchButton_src_off
           @see #ImageTextSwitchButton_text_off
         */
        public static final int[] ImageTextSwitchButton = {
            0x7f010000, 0x7f010001
        };
        /**
          <p>This symbol is the offset where the {@link org.tribosmap.R.attr#src_off}
          attribute's value can be found in the {@link #ImageTextSwitchButton} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:src_off
        */
        public static final int ImageTextSwitchButton_src_off = 1;
        /**
          <p>This symbol is the offset where the {@link org.tribosmap.R.attr#text_off}
          attribute's value can be found in the {@link #ImageTextSwitchButton} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:text_off
        */
        public static final int ImageTextSwitchButton_text_off = 0;
        /** Attributes that can be used with a ViewWrapper.
           <p>Includes the following attributes:</p>
           <table border="2" width="85%" align="center" frame="hsides" rules="all" cellpadding="5">
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute<th>Summary</tr>
           <tr><th><code>{@link #ViewWrapper_wrapLayout org.tribosmap:wrapLayout}</code><td></tr>
           </table>
           @see #ViewWrapper_wrapLayout
         */
        public static final int[] ViewWrapper = {
            0x7f010005
        };
        /**
          <p>This symbol is the offset where the {@link org.tribosmap.R.attr#wrapLayout}
          attribute's value can be found in the {@link #ViewWrapper} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:wrapLayout
        */
        public static final int ViewWrapper_wrapLayout = 0;
    };
}
