/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.tribosmap.testactivity;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int background=0x7f020007;
        public static final int greenball_small=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int myprogress=0x7f020002;
        public static final int myprogress_failure=0x7f020003;
        public static final int plus=0x7f020004;
        public static final int redball_small=0x7f020005;
        public static final int selected=0x7f020006;
        public static final int white=0x7f020008;
    }
    public static final class id {
        public static final int errorCounter=0x7f050008;
        public static final int errortext=0x7f050001;
        public static final int failureCounter=0x7f050009;
        public static final int launch_button=0x7f05000a;
        public static final int progress_bar=0x7f050004;
        public static final int row_icon=0x7f050002;
        public static final int row_title=0x7f050003;
        public static final int stacktracebtn=0x7f050000;
        public static final int status=0x7f050005;
        public static final int stop_button=0x7f05000b;
        public static final int testCounter=0x7f050006;
        public static final int totalCount=0x7f050007;
    }
    public static final class layout {
        public static final int error_dialog=0x7f030000;
        public static final int list_entry=0x7f030001;
        public static final int main=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int launch_test=0x7f040002;
        public static final int stop_test=0x7f040003;
    }
}
